USE [Higo.Game.GD]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_T_WeiTou_BillWash]    Script Date: 2018-08-11 17:29:51 ******/
CREATE NONCLUSTERED INDEX [IX_T_WeiTou_BillWash] ON [dbo].[T_WeiTou_BillWash]
(
	[ClientID] ASC,
	[AgentID3Bao] ASC,
	[StatisticsDay] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

