//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model.SqliteModel
{
    /// <summary>
    /// 实体类T_Config。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("T_Config")]
    [Serializable]
    public partial class T_Config : Entity
    {
        #region Model
		private int _id;
		private string _Ip;
		private int _Port;
		private int _IsAutoCut;
		private int _AutoCutTime;
		private string _LockPass;
		private string _RecIp;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Ip")]
		public string Ip
		{
			get{ return _Ip; }
			set
			{
				this.OnPropertyValueChange("Ip");
				this._Ip = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Port")]
		public int Port
		{
			get{ return _Port; }
			set
			{
				this.OnPropertyValueChange("Port");
				this._Port = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IsAutoCut")]
		public int IsAutoCut
		{
			get{ return _IsAutoCut; }
			set
			{
				this.OnPropertyValueChange("IsAutoCut");
				this._IsAutoCut = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AutoCutTime")]
		public int AutoCutTime
		{
			get{ return _AutoCutTime; }
			set
			{
				this.OnPropertyValueChange("AutoCutTime");
				this._AutoCutTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LockPass")]
		public string LockPass
		{
			get{ return _LockPass; }
			set
			{
				this.OnPropertyValueChange("LockPass");
				this._LockPass = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RecIp")]
		public string RecIp
		{
			get{ return _RecIp; }
			set
			{
				this.OnPropertyValueChange("RecIp");
				this._RecIp = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.Ip,
				_.Port,
				_.IsAutoCut,
				_.AutoCutTime,
				_.LockPass,
				_.RecIp,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._Ip,
				this._Port,
				this._IsAutoCut,
				this._AutoCutTime,
				this._LockPass,
				this._RecIp,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "T_Config");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "T_Config", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Ip = new Field("Ip", "T_Config", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Port = new Field("Port", "T_Config", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IsAutoCut = new Field("IsAutoCut", "T_Config", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AutoCutTime = new Field("AutoCutTime", "T_Config", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field LockPass = new Field("LockPass", "T_Config", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field RecIp = new Field("RecIp", "T_Config", "");
        }
        #endregion
	}
}