//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model.DBModel
{
    /// <summary>
    /// 实体类T_AgentSub。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("T_AgentSub")]
    [Serializable]
    public partial class T_AgentSub : Entity
    {
        #region Model
		private string _AgentSubID;
		private string _AgentID;
		private string _LogName;
		private string _Pwd;
		private string _State;
		private string _AgentSubName;

		/// <summary>
		/// 代理子账户编号
		/// </summary>
		[Field("AgentSubID")]
		public string AgentSubID
		{
			get{ return _AgentSubID; }
			set
			{
				this.OnPropertyValueChange("AgentSubID");
				this._AgentSubID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AgentID")]
		public string AgentID
		{
			get{ return _AgentID; }
			set
			{
				this.OnPropertyValueChange("AgentID");
				this._AgentID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LogName")]
		public string LogName
		{
			get{ return _LogName; }
			set
			{
				this.OnPropertyValueChange("LogName");
				this._LogName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Pwd")]
		public string Pwd
		{
			get{ return _Pwd; }
			set
			{
				this.OnPropertyValueChange("Pwd");
				this._Pwd = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("State")]
		public string State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange("State");
				this._State = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AgentSubName")]
		public string AgentSubName
		{
			get{ return _AgentSubName; }
			set
			{
				this.OnPropertyValueChange("AgentSubName");
				this._AgentSubName = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.AgentSubID,
				_.AgentID,
				_.LogName,
				_.Pwd,
				_.State,
				_.AgentSubName,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._AgentSubID,
				this._AgentID,
				this._LogName,
				this._Pwd,
				this._State,
				this._AgentSubName,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "T_AgentSub");
            /// <summary>
			/// 代理子账户编号
			/// </summary>
			public readonly static Field AgentSubID = new Field("AgentSubID", "T_AgentSub", "代理子账户编号");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AgentID = new Field("AgentID", "T_AgentSub", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field LogName = new Field("LogName", "T_AgentSub", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Pwd = new Field("Pwd", "T_AgentSub", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State", "T_AgentSub", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AgentSubName = new Field("AgentSubName", "T_AgentSub", "");
        }
        #endregion
	}
}