//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model.DBModel
{
    /// <summary>
    /// 实体类T_Authority。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("T_Authority")]
    [Serializable]
    public partial class T_Authority : Entity
    {
        #region Model
		private string _ClientID;
		private string _TableID;
		private string _Priority;
		private int? _Max_Z;
		private int? _Min_Z;
		private int? _Max_X;
		private int? _Min_X;
		private int? _Max_H;
		private int? _Min_H;
		private int? _Max_ZD;
		private int? _Min_ZD;
		private int? _Max_XD;
		private int? _Min_XD;

		/// <summary>
		/// 客户ID
		/// </summary>
		[Field("ClientID")]
		public string ClientID
		{
			get{ return _ClientID; }
			set
			{
				this.OnPropertyValueChange("ClientID");
				this._ClientID = value;
			}
		}
		/// <summary>
		/// 桌台ID
		/// </summary>
		[Field("TableID")]
		public string TableID
		{
			get{ return _TableID; }
			set
			{
				this.OnPropertyValueChange("TableID");
				this._TableID = value;
			}
		}
		/// <summary>
		/// 优先级        桌台(T)-代理(A)-客户(C)-自定义(P)
		/// </summary>
		[Field("Priority")]
		public string Priority
		{
			get{ return _Priority; }
			set
			{
				this.OnPropertyValueChange("Priority");
				this._Priority = value;
			}
		}
		/// <summary>
		/// 庄最大限红
		/// </summary>
		[Field("Max_Z")]
		public int? Max_Z
		{
			get{ return _Max_Z; }
			set
			{
				this.OnPropertyValueChange("Max_Z");
				this._Max_Z = value;
			}
		}
		/// <summary>
		/// 庄最小限红
		/// </summary>
		[Field("Min_Z")]
		public int? Min_Z
		{
			get{ return _Min_Z; }
			set
			{
				this.OnPropertyValueChange("Min_Z");
				this._Min_Z = value;
			}
		}
		/// <summary>
		/// 闲最大限红
		/// </summary>
		[Field("Max_X")]
		public int? Max_X
		{
			get{ return _Max_X; }
			set
			{
				this.OnPropertyValueChange("Max_X");
				this._Max_X = value;
			}
		}
		/// <summary>
		/// 闲最小限红
		/// </summary>
		[Field("Min_X")]
		public int? Min_X
		{
			get{ return _Min_X; }
			set
			{
				this.OnPropertyValueChange("Min_X");
				this._Min_X = value;
			}
		}
		/// <summary>
		/// 和最大限红
		/// </summary>
		[Field("Max_H")]
		public int? Max_H
		{
			get{ return _Max_H; }
			set
			{
				this.OnPropertyValueChange("Max_H");
				this._Max_H = value;
			}
		}
		/// <summary>
		/// 和最小限红
		/// </summary>
		[Field("Min_H")]
		public int? Min_H
		{
			get{ return _Min_H; }
			set
			{
				this.OnPropertyValueChange("Min_H");
				this._Min_H = value;
			}
		}
		/// <summary>
		/// 庄对最大限红
		/// </summary>
		[Field("Max_ZD")]
		public int? Max_ZD
		{
			get{ return _Max_ZD; }
			set
			{
				this.OnPropertyValueChange("Max_ZD");
				this._Max_ZD = value;
			}
		}
		/// <summary>
		/// 庄对最小限红
		/// </summary>
		[Field("Min_ZD")]
		public int? Min_ZD
		{
			get{ return _Min_ZD; }
			set
			{
				this.OnPropertyValueChange("Min_ZD");
				this._Min_ZD = value;
			}
		}
		/// <summary>
		/// 闲对最大限红
		/// </summary>
		[Field("Max_XD")]
		public int? Max_XD
		{
			get{ return _Max_XD; }
			set
			{
				this.OnPropertyValueChange("Max_XD");
				this._Max_XD = value;
			}
		}
		/// <summary>
		/// 闲对最小限红
		/// </summary>
		[Field("Min_XD")]
		public int? Min_XD
		{
			get{ return _Min_XD; }
			set
			{
				this.OnPropertyValueChange("Min_XD");
				this._Min_XD = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ClientID,
				_.TableID,
				_.Priority,
				_.Max_Z,
				_.Min_Z,
				_.Max_X,
				_.Min_X,
				_.Max_H,
				_.Min_H,
				_.Max_ZD,
				_.Min_ZD,
				_.Max_XD,
				_.Min_XD,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ClientID,
				this._TableID,
				this._Priority,
				this._Max_Z,
				this._Min_Z,
				this._Max_X,
				this._Min_X,
				this._Max_H,
				this._Min_H,
				this._Max_ZD,
				this._Min_ZD,
				this._Max_XD,
				this._Min_XD,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "T_Authority");
            /// <summary>
			/// 客户ID
			/// </summary>
			public readonly static Field ClientID = new Field("ClientID", "T_Authority", "客户ID");
            /// <summary>
			/// 桌台ID
			/// </summary>
			public readonly static Field TableID = new Field("TableID", "T_Authority", "桌台ID");
            /// <summary>
			/// 优先级        桌台(T)-代理(A)-客户(C)-自定义(P)
			/// </summary>
			public readonly static Field Priority = new Field("Priority", "T_Authority", "优先级        桌台(T)-代理(A)-客户(C)-自定义(P)");
            /// <summary>
			/// 庄最大限红
			/// </summary>
			public readonly static Field Max_Z = new Field("Max_Z", "T_Authority", "庄最大限红");
            /// <summary>
			/// 庄最小限红
			/// </summary>
			public readonly static Field Min_Z = new Field("Min_Z", "T_Authority", "庄最小限红");
            /// <summary>
			/// 闲最大限红
			/// </summary>
			public readonly static Field Max_X = new Field("Max_X", "T_Authority", "闲最大限红");
            /// <summary>
			/// 闲最小限红
			/// </summary>
			public readonly static Field Min_X = new Field("Min_X", "T_Authority", "闲最小限红");
            /// <summary>
			/// 和最大限红
			/// </summary>
			public readonly static Field Max_H = new Field("Max_H", "T_Authority", "和最大限红");
            /// <summary>
			/// 和最小限红
			/// </summary>
			public readonly static Field Min_H = new Field("Min_H", "T_Authority", "和最小限红");
            /// <summary>
			/// 庄对最大限红
			/// </summary>
			public readonly static Field Max_ZD = new Field("Max_ZD", "T_Authority", "庄对最大限红");
            /// <summary>
			/// 庄对最小限红
			/// </summary>
			public readonly static Field Min_ZD = new Field("Min_ZD", "T_Authority", "庄对最小限红");
            /// <summary>
			/// 闲对最大限红
			/// </summary>
			public readonly static Field Max_XD = new Field("Max_XD", "T_Authority", "闲对最大限红");
            /// <summary>
			/// 闲对最小限红
			/// </summary>
			public readonly static Field Min_XD = new Field("Min_XD", "T_Authority", "闲对最小限红");
        }
        #endregion
	}
}