//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model.DBModel
{
    /// <summary>
    /// 实体类T_ClientEx。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("T_ClientEx")]
    [Serializable]
    public partial class T_ClientEx : Entity
    {
        #region Model
		private string _ClientID;
		private int? _ClientDataShow;
		private decimal? _Odds_X_Client;
		private decimal? _Odds_XD_Client;
		private decimal? _Odds_Z_Client;
		private decimal? _Odds_ZD_Client;
		private decimal? _Odds_H_Client;
		private decimal? _Odds_Fu_Client;
		private decimal? _Odds_Long_Client;
		private decimal? _Odds_He_Client;
		private string _lastPlayDay;
		private string _Ex_1;
		private string _Ex_2;
		private string _Ex_3;

		/// <summary>
		/// 
		/// </summary>
		[Field("ClientID")]
		public string ClientID
		{
			get{ return _ClientID; }
			set
			{
				this.OnPropertyValueChange("ClientID");
				this._ClientID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ClientDataShow")]
		public int? ClientDataShow
		{
			get{ return _ClientDataShow; }
			set
			{
				this.OnPropertyValueChange("ClientDataShow");
				this._ClientDataShow = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Odds_X_Client")]
		public decimal? Odds_X_Client
		{
			get{ return _Odds_X_Client; }
			set
			{
				this.OnPropertyValueChange("Odds_X_Client");
				this._Odds_X_Client = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Odds_XD_Client")]
		public decimal? Odds_XD_Client
		{
			get{ return _Odds_XD_Client; }
			set
			{
				this.OnPropertyValueChange("Odds_XD_Client");
				this._Odds_XD_Client = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Odds_Z_Client")]
		public decimal? Odds_Z_Client
		{
			get{ return _Odds_Z_Client; }
			set
			{
				this.OnPropertyValueChange("Odds_Z_Client");
				this._Odds_Z_Client = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Odds_ZD_Client")]
		public decimal? Odds_ZD_Client
		{
			get{ return _Odds_ZD_Client; }
			set
			{
				this.OnPropertyValueChange("Odds_ZD_Client");
				this._Odds_ZD_Client = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Odds_H_Client")]
		public decimal? Odds_H_Client
		{
			get{ return _Odds_H_Client; }
			set
			{
				this.OnPropertyValueChange("Odds_H_Client");
				this._Odds_H_Client = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Odds_Fu_Client")]
		public decimal? Odds_Fu_Client
		{
			get{ return _Odds_Fu_Client; }
			set
			{
				this.OnPropertyValueChange("Odds_Fu_Client");
				this._Odds_Fu_Client = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Odds_Long_Client")]
		public decimal? Odds_Long_Client
		{
			get{ return _Odds_Long_Client; }
			set
			{
				this.OnPropertyValueChange("Odds_Long_Client");
				this._Odds_Long_Client = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Odds_He_Client")]
		public decimal? Odds_He_Client
		{
			get{ return _Odds_He_Client; }
			set
			{
				this.OnPropertyValueChange("Odds_He_Client");
				this._Odds_He_Client = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("lastPlayDay")]
		public string lastPlayDay
		{
			get{ return _lastPlayDay; }
			set
			{
				this.OnPropertyValueChange("lastPlayDay");
				this._lastPlayDay = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Ex_1")]
		public string Ex_1
		{
			get{ return _Ex_1; }
			set
			{
				this.OnPropertyValueChange("Ex_1");
				this._Ex_1 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Ex_2")]
		public string Ex_2
		{
			get{ return _Ex_2; }
			set
			{
				this.OnPropertyValueChange("Ex_2");
				this._Ex_2 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Ex_3")]
		public string Ex_3
		{
			get{ return _Ex_3; }
			set
			{
				this.OnPropertyValueChange("Ex_3");
				this._Ex_3 = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ClientID,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ClientID,
				_.ClientDataShow,
				_.Odds_X_Client,
				_.Odds_XD_Client,
				_.Odds_Z_Client,
				_.Odds_ZD_Client,
				_.Odds_H_Client,
				_.Odds_Fu_Client,
				_.Odds_Long_Client,
				_.Odds_He_Client,
				_.lastPlayDay,
				_.Ex_1,
				_.Ex_2,
				_.Ex_3,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ClientID,
				this._ClientDataShow,
				this._Odds_X_Client,
				this._Odds_XD_Client,
				this._Odds_Z_Client,
				this._Odds_ZD_Client,
				this._Odds_H_Client,
				this._Odds_Fu_Client,
				this._Odds_Long_Client,
				this._Odds_He_Client,
				this._lastPlayDay,
				this._Ex_1,
				this._Ex_2,
				this._Ex_3,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "T_ClientEx");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ClientID = new Field("ClientID", "T_ClientEx", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ClientDataShow = new Field("ClientDataShow", "T_ClientEx", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Odds_X_Client = new Field("Odds_X_Client", "T_ClientEx", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Odds_XD_Client = new Field("Odds_XD_Client", "T_ClientEx", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Odds_Z_Client = new Field("Odds_Z_Client", "T_ClientEx", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Odds_ZD_Client = new Field("Odds_ZD_Client", "T_ClientEx", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Odds_H_Client = new Field("Odds_H_Client", "T_ClientEx", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Odds_Fu_Client = new Field("Odds_Fu_Client", "T_ClientEx", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Odds_Long_Client = new Field("Odds_Long_Client", "T_ClientEx", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Odds_He_Client = new Field("Odds_He_Client", "T_ClientEx", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field lastPlayDay = new Field("lastPlayDay", "T_ClientEx", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Ex_1 = new Field("Ex_1", "T_ClientEx", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Ex_2 = new Field("Ex_2", "T_ClientEx", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Ex_3 = new Field("Ex_3", "T_ClientEx", "");
        }
        #endregion
	}
}