//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model.DBModel
{
    /// <summary>
    /// 实体类T_LoginLog。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("T_LoginLog")]
    [Serializable]
    public partial class T_LoginLog : Entity
    {
        #region Model
		private string _LogID;
		private string _UserLevel;
		private string _ParentAgent;
		private string _LoginIP;
		private string _LoginAddre;
		private string _LoginTime;
		private string _ReMark;
		private string _F_1;
		private string _LoginUser;

		/// <summary>
		/// 
		/// </summary>
		[Field("LogID")]
		public string LogID
		{
			get{ return _LogID; }
			set
			{
				this.OnPropertyValueChange("LogID");
				this._LogID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UserLevel")]
		public string UserLevel
		{
			get{ return _UserLevel; }
			set
			{
				this.OnPropertyValueChange("UserLevel");
				this._UserLevel = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ParentAgent")]
		public string ParentAgent
		{
			get{ return _ParentAgent; }
			set
			{
				this.OnPropertyValueChange("ParentAgent");
				this._ParentAgent = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LoginIP")]
		public string LoginIP
		{
			get{ return _LoginIP; }
			set
			{
				this.OnPropertyValueChange("LoginIP");
				this._LoginIP = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LoginAddre")]
		public string LoginAddre
		{
			get{ return _LoginAddre; }
			set
			{
				this.OnPropertyValueChange("LoginAddre");
				this._LoginAddre = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LoginTime")]
		public string LoginTime
		{
			get{ return _LoginTime; }
			set
			{
				this.OnPropertyValueChange("LoginTime");
				this._LoginTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ReMark")]
		public string ReMark
		{
			get{ return _ReMark; }
			set
			{
				this.OnPropertyValueChange("ReMark");
				this._ReMark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("F_1")]
		public string F_1
		{
			get{ return _F_1; }
			set
			{
				this.OnPropertyValueChange("F_1");
				this._F_1 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LoginUser")]
		public string LoginUser
		{
			get{ return _LoginUser; }
			set
			{
				this.OnPropertyValueChange("LoginUser");
				this._LoginUser = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.LogID,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.LogID,
				_.UserLevel,
				_.ParentAgent,
				_.LoginIP,
				_.LoginAddre,
				_.LoginTime,
				_.ReMark,
				_.F_1,
				_.LoginUser,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._LogID,
				this._UserLevel,
				this._ParentAgent,
				this._LoginIP,
				this._LoginAddre,
				this._LoginTime,
				this._ReMark,
				this._F_1,
				this._LoginUser,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "T_LoginLog");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field LogID = new Field("LogID", "T_LoginLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UserLevel = new Field("UserLevel", "T_LoginLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ParentAgent = new Field("ParentAgent", "T_LoginLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field LoginIP = new Field("LoginIP", "T_LoginLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field LoginAddre = new Field("LoginAddre", "T_LoginLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field LoginTime = new Field("LoginTime", "T_LoginLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ReMark = new Field("ReMark", "T_LoginLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field F_1 = new Field("F_1", "T_LoginLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field LoginUser = new Field("LoginUser", "T_LoginLog", "");
        }
        #endregion
	}
}