//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model.DBModel
{
    /// <summary>
    /// 实体类T_OperationLog。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("T_OperationLog")]
    [Serializable]
    public partial class T_OperationLog : Entity
    {
        #region Model
		private string _LogID;
		private string _LogTime;
		private string _LogType;
		private string _LogInfo;
		private string _OpID;
		private string _F1;
		private string _F2;
		private string _F3;

		/// <summary>
		/// 日志编号
		/// </summary>
		[Field("LogID")]
		public string LogID
		{
			get{ return _LogID; }
			set
			{
				this.OnPropertyValueChange("LogID");
				this._LogID = value;
			}
		}
		/// <summary>
		/// 操作时间
		/// </summary>
		[Field("LogTime")]
		public string LogTime
		{
			get{ return _LogTime; }
			set
			{
				this.OnPropertyValueChange("LogTime");
				this._LogTime = value;
			}
		}
		/// <summary>
		/// 操作类型
		/// </summary>
		[Field("LogType")]
		public string LogType
		{
			get{ return _LogType; }
			set
			{
				this.OnPropertyValueChange("LogType");
				this._LogType = value;
			}
		}
		/// <summary>
		/// 操作信息
		/// </summary>
		[Field("LogInfo")]
		public string LogInfo
		{
			get{ return _LogInfo; }
			set
			{
				this.OnPropertyValueChange("LogInfo");
				this._LogInfo = value;
			}
		}
		/// <summary>
		/// 操作人员编号
		/// </summary>
		[Field("OpID")]
		public string OpID
		{
			get{ return _OpID; }
			set
			{
				this.OnPropertyValueChange("OpID");
				this._OpID = value;
			}
		}
		/// <summary>
		/// 备用字段
		/// </summary>
		[Field("F1")]
		public string F1
		{
			get{ return _F1; }
			set
			{
				this.OnPropertyValueChange("F1");
				this._F1 = value;
			}
		}
		/// <summary>
		/// 备用字段
		/// </summary>
		[Field("F2")]
		public string F2
		{
			get{ return _F2; }
			set
			{
				this.OnPropertyValueChange("F2");
				this._F2 = value;
			}
		}
		/// <summary>
		/// 备用字段
		/// </summary>
		[Field("F3")]
		public string F3
		{
			get{ return _F3; }
			set
			{
				this.OnPropertyValueChange("F3");
				this._F3 = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.LogID,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.LogID,
				_.LogTime,
				_.LogType,
				_.LogInfo,
				_.OpID,
				_.F1,
				_.F2,
				_.F3,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._LogID,
				this._LogTime,
				this._LogType,
				this._LogInfo,
				this._OpID,
				this._F1,
				this._F2,
				this._F3,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "T_OperationLog");
            /// <summary>
			/// 日志编号
			/// </summary>
			public readonly static Field LogID = new Field("LogID", "T_OperationLog", "日志编号");
            /// <summary>
			/// 操作时间
			/// </summary>
			public readonly static Field LogTime = new Field("LogTime", "T_OperationLog", "操作时间");
            /// <summary>
			/// 操作类型
			/// </summary>
			public readonly static Field LogType = new Field("LogType", "T_OperationLog", "操作类型");
            /// <summary>
			/// 操作信息
			/// </summary>
			public readonly static Field LogInfo = new Field("LogInfo", "T_OperationLog", "操作信息");
            /// <summary>
			/// 操作人员编号
			/// </summary>
			public readonly static Field OpID = new Field("OpID", "T_OperationLog", "操作人员编号");
            /// <summary>
			/// 备用字段
			/// </summary>
			public readonly static Field F1 = new Field("F1", "T_OperationLog", "备用字段");
            /// <summary>
			/// 备用字段
			/// </summary>
			public readonly static Field F2 = new Field("F2", "T_OperationLog", "备用字段");
            /// <summary>
			/// 备用字段
			/// </summary>
			public readonly static Field F3 = new Field("F3", "T_OperationLog", "备用字段");
        }
        #endregion
	}
}