//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model.DBModel
{
    /// <summary>
    /// 实体类T_SettleAccount。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("T_SettleAccount")]
    [Serializable]
    public partial class T_SettleAccount : Entity
    {
        #region Model
		private string _BillID;
		private string _Operator;
		private string _AccountSource;
		private string _AccountDest;
		private int? _AcCount;
		private decimal? _AcAmount;
		private string _AcRate;
		private decimal? _AcQuantity;
		private string _AcType;
		private string _StartDate;
		private string _Enddate;
		private string _AcDate;
		private string _AcState;

		/// <summary>
		/// 
		/// </summary>
		[Field("BillID")]
		public string BillID
		{
			get{ return _BillID; }
			set
			{
				this.OnPropertyValueChange("BillID");
				this._BillID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Operator")]
		public string Operator
		{
			get{ return _Operator; }
			set
			{
				this.OnPropertyValueChange("Operator");
				this._Operator = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AccountSource")]
		public string AccountSource
		{
			get{ return _AccountSource; }
			set
			{
				this.OnPropertyValueChange("AccountSource");
				this._AccountSource = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AccountDest")]
		public string AccountDest
		{
			get{ return _AccountDest; }
			set
			{
				this.OnPropertyValueChange("AccountDest");
				this._AccountDest = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AcCount")]
		public int? AcCount
		{
			get{ return _AcCount; }
			set
			{
				this.OnPropertyValueChange("AcCount");
				this._AcCount = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AcAmount")]
		public decimal? AcAmount
		{
			get{ return _AcAmount; }
			set
			{
				this.OnPropertyValueChange("AcAmount");
				this._AcAmount = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AcRate")]
		public string AcRate
		{
			get{ return _AcRate; }
			set
			{
				this.OnPropertyValueChange("AcRate");
				this._AcRate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AcQuantity")]
		public decimal? AcQuantity
		{
			get{ return _AcQuantity; }
			set
			{
				this.OnPropertyValueChange("AcQuantity");
				this._AcQuantity = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AcType")]
		public string AcType
		{
			get{ return _AcType; }
			set
			{
				this.OnPropertyValueChange("AcType");
				this._AcType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("StartDate")]
		public string StartDate
		{
			get{ return _StartDate; }
			set
			{
				this.OnPropertyValueChange("StartDate");
				this._StartDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Enddate")]
		public string Enddate
		{
			get{ return _Enddate; }
			set
			{
				this.OnPropertyValueChange("Enddate");
				this._Enddate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AcDate")]
		public string AcDate
		{
			get{ return _AcDate; }
			set
			{
				this.OnPropertyValueChange("AcDate");
				this._AcDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AcState")]
		public string AcState
		{
			get{ return _AcState; }
			set
			{
				this.OnPropertyValueChange("AcState");
				this._AcState = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.BillID,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.BillID,
				_.Operator,
				_.AccountSource,
				_.AccountDest,
				_.AcCount,
				_.AcAmount,
				_.AcRate,
				_.AcQuantity,
				_.AcType,
				_.StartDate,
				_.Enddate,
				_.AcDate,
				_.AcState,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._BillID,
				this._Operator,
				this._AccountSource,
				this._AccountDest,
				this._AcCount,
				this._AcAmount,
				this._AcRate,
				this._AcQuantity,
				this._AcType,
				this._StartDate,
				this._Enddate,
				this._AcDate,
				this._AcState,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "T_SettleAccount");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field BillID = new Field("BillID", "T_SettleAccount", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Operator = new Field("Operator", "T_SettleAccount", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AccountSource = new Field("AccountSource", "T_SettleAccount", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AccountDest = new Field("AccountDest", "T_SettleAccount", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AcCount = new Field("AcCount", "T_SettleAccount", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AcAmount = new Field("AcAmount", "T_SettleAccount", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AcRate = new Field("AcRate", "T_SettleAccount", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AcQuantity = new Field("AcQuantity", "T_SettleAccount", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AcType = new Field("AcType", "T_SettleAccount", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field StartDate = new Field("StartDate", "T_SettleAccount", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Enddate = new Field("Enddate", "T_SettleAccount", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AcDate = new Field("AcDate", "T_SettleAccount", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AcState = new Field("AcState", "T_SettleAccount", "");
        }
        #endregion
	}
}